### ISSUE TITLE
トップページとヘッダー製作

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#12]
#10 で決めたレイアウトを基に作成してください！

ヘッダーは他のページでも使えるようにテンプレート化をお願いします。

# 具体的な仕様
- ヘッダーはログインの前後で表示するものが変わる
  - ログイン前
    - ログイン
    - 会員登録
  - ログイン後
    - ログアウト
    - アカウント削除

@morita-32 
@momo-717 

トップページはお二人にお任せしたいと思います！
よろしくお願いします！

# TODO
- [x] `index.php`に記述
- [x] `css/style.scss`に記述
- [x] `templates/header.php`を作成して記述
- [x] `templates/css/header.php`を作成して記述

**Comment by morita-32** [comment]
@Toshiki428 
ヘッダーのデザインの指定は特になしですか？

**Comment by Toshiki428** [comment]
@morita-32 
カラーは
- `#ffffff`
- `#0075ff`
の2色でお願いします！

その他デザインはお任せします！

**Comment by morita-32** [comment]
@Toshiki428 
作成するブランチの名前は何でも大丈夫？
作るブランチの数は2つかな？

**Comment by Toshiki428** [comment]
@morita-32 
headerブランチとtopブランチの2つでお願いします！

**Comment by morita-32** [comment]
@Toshiki428 
headerブランチとtopブランチでの作業がほぼ完了しました

**Comment by Toshiki428** [comment]
@morita-32 
OKです！
レビューしようと思うのでプルリクエストをお願いします！

レビューは夜になってしまうので、その間、時間があればゲーム制作の準備を進めてください！
