### ISSUE TITLE
会員登録ページ製作

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#13]
ヘッダーは別ファイルからincludeするので作成しなくて大丈夫です！

会員登録ページとログインページは同じcssファイルを適用しようと思うので、
適宜グループ間でコミュニケーションをとって進めてください。

完成レイアウトはこのような形で、ボタンの色は`#0075ff`でお願いします！
ログインの部分は会員登録に置き換えてください。
![ログイン](https://github.com/HAL-OSAKA-IT/game_collect/assets/109594862/73f4e59a-7c46-4031-b2c3-577151bb5e9f)

簡単にCLASS名やID名を指定しておきます！

![ログイン1](https://github.com/HAL-OSAKA-IT/game_collect/assets/109594862/b9093738-cd52-4d82-bf7f-52dc3d297903)

# 仕様
- ユーザーネームとパスワードを入力して会員登録できる

@okinopita 
@k4izu 

会員登録ページはお二人にお任せしたいと思います！
よろしくお願いします！

# TODO
- [x] `registration`ブランチを作成
- [x] `member/registration.php`を作成して記述
- [x] `member/css/form.scss`を作成
- [x] `member/css/form.scss`を記述
- [x] 入力した情報をデータベースに登録できるようにする

**Comment by okinopita** [comment]
@Toshiki428 
質問と報告です。
- 会員のデータについて、issueでのイメージ上ではメールアドレス、データベース上のカラム名ではnameになっていますが、どちらに揃えた方が良いですか。門脇君は設計時にはnameカラムがvarchar(15)だったのでおそらくメールアドレスは想定していないのかなと思っています。

- VSCodeのsettings.jsonに以下のLive Sass Compilerの設定を記述しないと、`member/css/style.scss`を編集した際に同じファイル名のstyle.scssのファイルの階層にもcssファイルが生成されてしまったので、共有します。(必要があれば別のグループにも共有します。)
`
    "liveSassCompile.settings.forceBaseDirectory": null
`

**Comment by Toshiki428** [comment]
> 会員のデータについて、issueでのイメージ上ではメールアドレス、データベース上のカラム名ではnameになっていますが、どちらに揃えた方が良いですか。

画像は、すでにあるサイトからスクリーンショットで取ってきてるだけなのでメールアドレスになってしまっていますが、ユーザー名とパスワードでログインすることになります！あくまでレイアウトのイメージ用の画像だと思ってください！

> `member/css/style.scss`を編集した際に同じファイル名のstyle.scssのファイルの階層にもcssファイルが生成されてしまった

`game_collect/css/style.scss`にcssファイルが生成されたということであってますか？

**Comment by okinopita** [comment]
> 画像は、すでにあるサイトからスクリーンショットで取ってきてるだけなのでメールアドレスになってしまっていますが、ユーザー名とパスワードでログインすることになります！あくまでレイアウトのイメージ用の画像だと思ってください！   

分かりました。
> game_collect/css/style.scssにcssファイルが生成されたということであってますか？   

それで合っています。

**Comment by Toshiki428** [comment]
承知しました！

全員のVSCodeの設定を変えることは難しいので、scssファイルの名前を変えることで対応しましょう！

`member/css/style.scss`となっているのを、`member/css/form.scss`に変更して対応をお願いします！

**Comment by k4izu** [comment]
会員登録後はindex.phpまたは、登録完了の画面に移動する形になると思いますが、ページ遷移の指定はありますか？

**Comment by Toshiki428** [comment]
@k4izu 
ひとまずindex.phpへの遷移を、お願いします！
実際に動かしてみて、別の遷移がよさそうであればそこで対応しようと思います！
