### ISSUE TITLE
ログインページ作成

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#14]
ヘッダーは別ファイルからincludeするので作成しなくて大丈夫です！

会員登録ページとログインページは同じcssファイルを適用しようと思うので、
適宜グループ間でコミュニケーションをとって進めてください。

完成レイアウトはこのような形で、ボタンの色は`#0075ff`でお願いします！
![ログイン](https://github.com/HAL-OSAKA-IT/game_collect/assets/109594862/7185942c-d3aa-4bf1-9607-743736a19c74)

簡単にCLASS名やID名を指定しておきます！
![ログイン1](https://github.com/HAL-OSAKA-IT/game_collect/assets/109594862/1b148cec-527f-44cf-8f14-d50ca470d613)

# 仕様
- 会員登録されている情報と照らし合わせてログインできる

@jmn04 
@shogo80 

ログインページはお二人に任せたいと思います。
よろしくお願いします！

# TODO
- [x] loginブランチを作成
- [x] member/login.phpを作成して記述
- [x] member/css/form.scssを作成
- [x] member/css/form.scssを記述
- [x] データベースにテストデータを挿入して、ログインできるようにする

**Comment by Toshiki428** [comment]
新規メンバー登録となっている部分は**新規会員登録に統一**をお願いします！

**Comment by Toshiki428** [comment]
`game_collect/member/css/style.scss`を編集した際に、同じ名前の`game_collect/css/style.scss`のCSSファイルが同時に生成されてしまうようです！

そこで`member/css/style.scss`を`member/css/form.scss`に変更して対応しようと思います！

変更をお願いします！

**Comment by shogo80** [comment]
了解です。

2023年12月16日(土) 18:31 Toshiki Wata ***@***.***>:
