### ISSUE TITLE
ベースのファイル作成

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#6]
今は`README.md`しかファイルが存在しないので、最低限必要なファイルの作成をお願いします！

# TODO
- [x] index.phpの作成（リセットCSSの適用までお願いします。bodyの中には何も記載しなくてOKです！）
- [x] css/destyle.cssの作成
- [x] css/style.scssの作成（スタイルの記載はまた別で仕事を振るのでしなくてOKです！）
- [x] js/script.jsの作成（こちらも内容の記載は必要ないです！）

**Comment by Toshiki428** [comment]
@jmn04 
この仕事は門脇君にお願いしようかなと思っているのですが大丈夫ですか？

**Comment by jmn04** [comment]
@Toshiki428 
了解です。

**Comment by Toshiki428** [comment]
じゃあお任せします！

恐らくmainブランチに直接プッシュできなくなってるので
baseブランチを作ってそこからプルリクエストをお願いします！

**Comment by jmn04** [comment]
@Toshiki428 
所定の作業完了。
baseブランチよりプルリクしました！

**Comment by Toshiki428** [comment]
@jmn04 
確認できました！

このプロジェクトでは機能ごとにブランチを作っていこうと思うので、マージを終えたブランチは基本的に消そうと思います！
今回はこちらで消しておきますね！

このメッセージが確認出来たら、右下の`Close with comment`から、このissueを閉じてください。
